name: 01 Basic Workflow
run-name: ${{ github.actor }}의 기초 워크플로우 실습

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@4

      - name: 메세지 출력
        run: echo "GitHub Actions Python Basic Workflow Running"

      - name: 현재 디렉토리 확인
        run: pwd
      
      - name: 디렉토리 내 파일 목록 확인
        run: ls -al