name: 05 Upload Artifact Workflow

on:
  push:
    branches:
      - '!main'

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 리포트 생성
        run: python generate_report.py

      - name: 리포트 파일 업로드
        uses: actions/upload-artifact@v4
        with:
          name: python-report
          path: report.txt