name: 07 Secret Workflow

on:
  push:
    branches:
      - 'main'

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Secret 사용 실행
        env:
          SECRET_MESSAGE: ${{ secrets.SECRET_MESSAGE }}
          SECRET_MESSAGE2: ''
        run: python secret_app.py